name: Build melashri/nopyterhub & Push to Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: melashri/nopyterhub:base
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: nopyter-hub/base/Dockerfile
